export const LLM_MAPPING = {
    "healthcare": "microsoft/phi-3-medium-128k-instruct:free",
    "mathematics": "meta-llama/llama-3.1-8b-instruct",
    "programming": "huggingfaceh4/zephyr-7b-beta:free",
    "creative writing": "mistralai/mistral-7b-instruct:free",
    "science": "qwen/qwen-2-7b-instruct:free",
    "reasoning": "meta-llama/llama-3.1-8b-instruct",
    "education": "meta-llama/llama-3.1-405b-instruct:free",
    "general knowledge": "huggingfaceh4/zephyr-7b-beta:free",
    "travel": "mistralai/mistral-7b-instruct:free",
    "entertainment": "qwen/qwen-2-7b-instruct:free",
    "finance": "microsoft/phi-3-medium-128k-instruct:free",
    "technology": "google/gemma-2-9b-it:free",
    "shopping": "huggingfaceh4/zephyr-7b-beta:free",
    "history": "meta-llama/llama-3.1-8b-instruct",
    "geography": "qwen/qwen-2-7b-instruct:free",
    "art": "mistralai/mistral-7b-instruct:free",
    "music": "mistralai/mistral-7b-instruct:free",
    "sports": "huggingfaceh4/zephyr-7b-beta:free",
    "fitness": "meta-llama/llama-3.1-70b-instruct:free",
    "food": "mistralai/mistral-7b-instruct:free",
    "childcare": "huggingfaceh4/zephyr-7b-beta:free",
    "language": "meta-llama/llama-3.2-3b-instruct:free",
    "business": "microsoft/phi-3-medium-128k-instruct:free",
    "marketing": "huggingfaceh4/zephyr-7b-beta:free",
    "job": "meta-llama/llama-3.1-405b-instruct:free",
    "diy": "huggingfaceh4/zephyr-7b-beta:free",
    "dating": "mistralai/mistral-7b-instruct:free",
    "psychology": "meta-llama/llama-3.1-405b-instruct",
    "law": "microsoft/phi-3-medium-128k-instruct:free",
    "environment": "meta-llama/llama-3.1-405b-instruct:free",
    "astronomy": "qwen/qwen-2-7b-instruct:free",
    "fashion": "mistralai/mistral-7b-instruct:free",
    "gaming": "qwen/qwen-2-7b-instruct:free",
    "mythology": "mistralai/mistral-7b-instruct:free",
    "religion": "mistralai/mistral-7b-instruct:free",
    "pets": "meta-llama/llama-3.1-70b-instruct:free",
    "advanced_programming": "meta-llama/llama-3.1-405b-instruct:free",
    "technical_writing": "google/gemma-2-9b-it:free",
}

export const SECONDARY_LLM_MAPPING = {
    "healthcare": "meta-llama/llama-3.1-70b-instruct:free",
    "mathematics": "qwen/qwen-2-7b-instruct:free",
    "programming": "google/gemma-2-9b-it:free",
    "creative writing": "meta-llama/llama-3.1-8b-instruct",
    "science": "meta-llama/llama-3.1-405b-instruct:free",
    "reasoning": "qwen/qwen-2-7b-instruct:free",
    "education": "mistralai/mistral-7b-instruct:free",
    "general knowledge": "meta-llama/llama-3.2-3b-instruct:free",
    "travel": "qwen/qwen-2-7b-instruct:free",
    "entertainment": "mistralai/mistral-7b-instruct:free",
    "finance": "meta-llama/llama-3.1-8b-instruct",
    "technology": "meta-llama/llama-3.1-405b-instruct:free",
    "shopping": "mistralai/mistral-7b-instruct:free",
    "history": "qwen/qwen-2-7b-instruct:free",
    "geography": "meta-llama/llama-3.1-8b-instruct",
    "art": "huggingfaceh4/zephyr-7b-beta:free",
    "music": "meta-llama/llama-3.2-3b-instruct:free",
    "sports": "qwen/qwen-2-7b-instruct:free",
    "fitness": "meta-llama/llama-3.2-3b-instruct:free",
    "food": "meta-llama/llama-3.1-8b-instruct",
    "childcare": "mistralai/mistral-7b-instruct:free",
    "language": "mistralai/mistral-7b-instruct:free",
    "business": "meta-llama/llama-3.2-3b-instruct:free",
    "marketing": "meta-llama/llama-3.1-405b-instruct:free",
    "job": "meta-llama/llama-3.1-8b-instruct",
    "diy": "qwen/qwen-2-7b-instruct:free",
    "dating": "meta-llama/llama-3.2-3b-instruct:free",
    "psychology": "mistralai/mistral-7b-instruct:free",
    "law": "meta-llama/llama-3.1-8b-instruct",
    "environment": "meta-llama/llama-3.2-3b-instruct:free",
    "astronomy": "meta-llama/llama-3.1-405b-instruct:free",
    "fashion": "meta-llama/llama-3.2-3b-instruct:free",
    "gaming": "huggingfaceh4/zephyr-7b-beta:free",
    "mythology": "meta-llama/llama-3.1-70b-instruct:free",
    "religion": "meta-llama/llama-3.1-8b-instruct",
    "pets": "qwen/qwen-2-7b-instruct:free"
}